//
//  ThirdViewController.swift
//  ConsultaCep
//
//  Created by mateusdias on 07/10/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ThirdViewController: UIViewController{
  
    @IBOutlet weak var zipCodeLabel: UILabel!
    @IBOutlet weak var addressLabel: UILabel!
    @IBOutlet weak var cityLabel: UILabel!
    @IBOutlet weak var ufLabel: UILabel!
    
    var zipCodeValue: String = ""
    var addressValue: String = ""
    var cityValue: String = ""
    var ufValue: String = ""
    
    override func viewDidLoad(){
    super.viewDidLoad()
        zipCodeLabel.text = zipCodeValue
        addressLabel.text = addressValue
        cityLabel.text = cityValue
        ufLabel.text = ufValue
  }
    @IBAction func reconsultAddress(_ sender: UIButton) {
        dismiss(animated: true, completion: nil)
    }
    
}
